window.TESTS = window.TESTS || [];
window.TESTS.push({
  name: "Intermediate Test 7",
  badge: "📗 Present Perfect · Prepositions · Vocabulary",
  questions: [
    { q: "1. I was born _______ 1974.", opts: ["for", "since", "in", "ago"], ans: 2, exp: "Signal: Specific year ('1974') -> Preposition 'in'." },
    { q: "2. I've been a journalist _______ two years.", opts: ["for", "since", "in", "ago"], ans: 0, exp: "Signal: A period of time ('two years') -> Preposition 'for'." },
    { q: "3. I waited for you _______ hours.", opts: ["for", "since", "in", "ago"], ans: 0, exp: "Signal: A period of time ('hours') -> Preposition 'for'." },
    { q: "4. She left university three years _______.", opts: ["for", "since", "in", "ago"], ans: 3, exp: "Signal: Past Simple ('left') + time span -> 'ago'." },
    { q: "5. He's lived abroad _______ 1990.", opts: ["for", "since", "in", "ago"], ans: 1, exp: "Signal: A specific point in time in the past ('1990') with Present Perfect -> 'since'." },
    { q: "6. They got acquainted with each other _______ last year.", opts: ["for", "since", "in", "-"], ans: 3, exp: "Signal: Time expressions with 'last', 'next', 'this' do not take prepositions -> no preposition (-)." },
    { q: "7. Have you _______ been to China?", opts: ["never", "ever", "since", "yet"], ans: 1, exp: "Signal: Question about life experience -> 'ever'." },
    { q: "8. Don't worry about phoning him because I've _______ done it.", opts: ["ever", "already", "yet", "never"], ans: 1, exp: "Signal: Action completed sooner than expected -> 'already'." },
    { q: "9. I haven't finished my lunch _______.", opts: ["never", "ever", "already", "yet"], ans: 3, exp: "Signal: Negative Present Perfect sentence, end of sentence -> 'yet'." },
    { q: "10. I've not _______ been skiing, but I'd like to try it.", opts: ["never", "ever", "already", "just"], ans: 1, exp: "Signal: 'not' + 'ever' = never. It means at any time up to now." },
    { q: "11. I can't come out because I've _______ washed my hair.", opts: ["never", "ever", "just", "yet"], ans: 2, exp: "Signal: A very recent action causing a present result -> 'just'." },
    { q: "12. Have you met our new teacher _______?", opts: ["just", "ever", "already", "yet"], ans: 3, exp: "Signal: Question expecting an action to have happened, end of sentence -> 'yet'." },
    { q: "13. I'm delighted because I've been _______ a pay rise.", opts: ["gave", "have given", "given", "was given"], ans: 2, exp: "Signal: Passive Present Perfect (I have been + V3) -> 'given'." },
    { q: "14. The director's children _______.", opts: ["have been kidnapped", "have kidnapped", "kidnapped", "was kidnapped"], ans: 0, exp: "Signal: 'children' (plural) + passive action -> 'have been kidnapped'." },
    { q: "15. They're really angry because someone _______ their car.", opts: ["has been damaged", "has damaged", "damage", "was damaged"], ans: 1, exp: "Signal: 'someone' (singular subject) + active action -> 'has damaged'." },
    { q: "16. She's going to be late because her plane _______.", opts: ["has been delayed", "has delayed", "delayed", "was delayed"], ans: 0, exp: "Signal: Passive action affecting the present ('going to be late') -> 'has been delayed'." },
    { q: "17. He _______ to a senior designer.", opts: ["has been promoted", "has promoted", "promoted", "are promoted"], ans: 0, exp: "Signal: Passive action ('promoted to') -> 'has been promoted'." },
    { q: "18. Hundreds of people _______ for the jobs.", opts: ["have been applied", "have applied", "have applying", "was applied"], ans: 1, exp: "Signal: 'people' (plural) + active action ('apply for') -> 'have applied'." },
    { q: "19. Four people _______ in a train crash.", opts: ["have been killed", "have killed", "are killed", "was killed"], ans: 0, exp: "Signal: 'people' (plural) + passive action -> 'have been killed'." },
    { q: "20. Local police _______ the bank robber.", opts: ["have been arrested", "have arrested", "has arrested", "was arrested"], ans: 1, exp: "Signal: 'police' is a plural noun + active action -> 'have arrested'." },
    { q: "21. Floods _______ serious damage.", opts: ["have been caused", "have caused", "has caused", "was caused"], ans: 1, exp: "Signal: 'Floods' (plural) + active action -> 'have caused'." },
    { q: "22. My job application _______.", opts: ["haven't been accepted", "haven't accepted", "hasn't been accepted", "hasn't accepted"], ans: 2, exp: "Signal: 'application' (singular) + passive action -> 'hasn't been accepted'." },
    { q: "23. The workers _______ a new representative.", opts: ["have been elected", "have elected", "has elected", "was elected"], ans: 1, exp: "Signal: 'workers' (plural) + active action -> 'have elected'." },
    { q: "24. An occupation which gives opportunities for promotion is a/an _______.", opts: ["applicant", "CV", "career", "retirement"], ans: 2, exp: "Vocabulary: A profession with advancement is a 'career'." },
    { q: "25. A document which lists your personal and professional details is a(n) _______.", opts: ["applicant", "CV", "application", "retirement"], ans: 1, exp: "Vocabulary: A document with details is a 'CV' (Curriculum Vitae)." },
    { q: "26. A person who has reached an age where they no longer work is _______.", opts: ["an applicant", "a CV", "an application", "retired"], ans: 3, exp: "Vocabulary: Stopping work due to age is being 'retired'." },
    { q: "27. When you want to leave a job, you have to give your _______.", opts: ["resignation", "Resume", "career", "retirement"], ans: 0, exp: "Vocabulary: Formal notice of leaving is a 'resignation'." },
    { q: "28. If you have the right talents and experience for a job, then you are _______ for it.", opts: ["resignation", "resume", "career", "qualified"], ans: 3, exp: "Vocabulary: Having the right skills means you are 'qualified'." },
    { q: "29. When you try and get a job, you usually have to complete a/an _______ form.", opts: ["resignation", "resume", "application", "retirement"], ans: 2, exp: "Vocabulary: The form you fill out to get a job is an 'application'." },
    { q: "30. If an employee is no longer needed, he or she can be made _______.", opts: ["resigned", "redundant", "employer", "retiring"], ans: 1, exp: "Vocabulary: To be dismissed because the job is no longer needed is to be 'made redundant'." },
    { q: "31. You can often find about a new job by a/an _______ in a newspaper.", opts: ["news", "completion", "sensation", "advertisement"], ans: 3, exp: "Vocabulary: A notice offering a job is an 'advertisement'." },
    { q: "32. If an employer is interested in meeting you, you will be asked to come to a/an _______.", opts: ["sensation", "add", "completion", "interview"], ans: 3, exp: "Vocabulary: A formal meeting for a job is an 'interview'." },
    { q: "33. Tom's just _______ to the area manager of Eastern Europe.", opts: ["promoted", "been promoted", "promoted", "to promote"], ans: 1, exp: "Signal: Passive Present Perfect ('has just been promoted')." },
    { q: "34. I _______ for a new job.", opts: ["have applied", "have been applied", "apply", "been applied"], ans: 0, exp: "Signal: Active Present Perfect ('have applied')." },
    { q: "35. How many times _______ redundant?", opts: ["were you", "have you been made", "you", "have you made"], ans: 1, exp: "Signal: 'How many times' (Life experience) + Passive -> 'have you been made'." },
    { q: "36. Bob's wife _______ her job.", opts: ["has lost", "were lost", "was losing", "has been lost"], ans: 0, exp: "Signal: Active Present Perfect ('has lost')." },
    { q: "37. My father _______ early retirement.", opts: ["was taken", "has taken", "has been taken", "take"], ans: 1, exp: "Signal: Active phrase 'take retirement' in Present Perfect -> 'has taken'." },
    { q: "38. My brother _______ the sack. His boss said he was lazy.", opts: ["has been given", "gave", "given", "has given"], ans: 0, exp: "Signal: Passive phrase 'be given the sack' (to be fired) in Present Perfect." },
    { q: "39. The number of people out of work _______ to nearly 3 million.", opts: ["has risen", "have risen", "have been risen", "has been risen"], ans: 0, exp: "Signal: 'The number of' takes a singular verb -> 'has risen'." },
    { q: "40. A strike _______ by the air traffic controllers.", opts: ["called", "has called", "has been called", "is given"], ans: 2, exp: "Signal: Passive Present Perfect (A strike has been called)." },
    { q: "41. They _______ more money by the management.", opts: ["haven't offered", "haven't been offered", "offer", "offered"], ans: 1, exp: "Signal: Passive Present Perfect ('haven't been offered')." },
    { q: "42. How much money _______ for your retirement?", opts: ["saved", "have you been saved", "have you saved", "you saved"], ans: 2, exp: "Signal: Question in Active Present Perfect -> 'have you saved'." },
    { q: "43. The factory workers are _______ strike because they want more money.", opts: ["in", "on", "out of", "of"], ans: 1, exp: "Vocabulary: Collocation 'on strike' (đình công)." },
    { q: "44. Thousands of people are _______ work in this town. It's really difficult to get a job.", opts: ["in", "on", "out of", "of"], ans: 2, exp: "Vocabulary: Collocation 'out of work' (unemployed)." },
    { q: "45. I got a cheque _______ a hundred pounds this morning.", opts: ["in", "on", "out of", "for"], ans: 3, exp: "Vocabulary: 'a cheque for' a certain amount of money." },
    { q: "46. You're really annoying me. You're doing it _______ purpose, aren't you?", opts: ["in", "on", "out of", "of"], ans: 1, exp: "Vocabulary: Collocation 'on purpose' (deliberately)." },
    { q: "47. Can you tell the difference _______ butter and margarine.", opts: ["between", "on", "out of", "of"], ans: 0, exp: "Vocabulary: 'difference between' two things." },
    { q: "48. There have been a lot of complaints _______ your behavior.", opts: ["in", "on", "out of", "about"], ans: 3, exp: "Vocabulary: 'complaints about' something." },
    { q: "49. You are always _______ trouble because you don't listen to anybody.", opts: ["in", "on", "with", "of"], ans: 0, exp: "Vocabulary: Collocation 'in trouble' (gặp rắc rối)." },
    { q: "50. I'm fed up _______ cooking. Let's eat _______ for a change.", opts: ["in / out", "on / now", "with / out", "at / out"], ans: 2, exp: "Vocabulary: 'fed up with' (chán ngấy) and 'eat out' (ăn nhà hàng)." },
    { q: "51. How much do you spend a week _______ average?", opts: ["in", "on", "out of", "of"], ans: 1, exp: "Vocabulary: Collocation 'on average' (trung bình)." },
    { q: "52. Watch your step with Dad. He's _______ a terrible mood.", opts: ["in", "on", "out of", "of"], ans: 0, exp: "Vocabulary: Collocation 'in a terrible mood' (tâm trạng rất tệ)." }
  ]
});
