window.TESTS = window.TESTS || [];
window.TESTS.push({
  name: "Pre-Intermediate 1",
  badge: "📙 Pronouns · Articles · Quantifiers",
  questions: [
    { q: "1. I can see Amanda. _______ is waiting for the New York plane.", opts: ["I", "She", "His", "He"], ans: 1, exp: "Signal: 'Amanda' (female) + Subject position -> Pronoun 'She'." },
    { q: "2. The clerk is speaking to the women. He is talking to _______.", opts: ["them", "they", "him", "he"], ans: 0, exp: "Signal: 'the women' (plural) + Object position (after 'to') -> Pronoun 'them'." },
    { q: "3. I haven't got the keys. Father has got _______.", opts: ["him", "her", "it", "them"], ans: 3, exp: "Signal: 'keys' (plural object) -> Object Pronoun 'them'." },
    { q: "4. Can you see those boys and _______ father?", opts: ["they", "them", "their", "him"], ans: 2, exp: "Signal: Noun 'father' needs a possessive adjective -> 'their'." },
    { q: "5. Today _______ weather is very hot.", opts: ["a", "an", "the", "-"], ans: 2, exp: "Signal: 'weather' is a specific, uncountable noun in context -> Article 'the'." },
    { q: "6. He is Mrs. Taylor's _______ husband.", opts: ["a", "-", "the", "an"], ans: 1, exp: "Signal: Possessive \"Mrs. Taylor's\" already exists -> No article (-)." },
    { q: "7. Butterflies are _______ insects.", opts: ["a", "an", "the", "-"], ans: 3, exp: "Signal: Plural noun ('insects') used in a general sense -> No article (-)." },
    { q: "8. Is a bee _______ insect?", opts: ["a", "an", "-", "the"], ans: 1, exp: "Signal: Singular countable noun starting with a vowel sound ('insect') -> 'an'." },
    { q: "9. I'll wait for you half _______ hour.", opts: ["-", "an", "a", "the"], ans: 1, exp: "Signal: 'hour' starts with a silent 'h' (vowel sound) -> 'an'." },
    { q: "10. I haven't got _______ paint.", opts: ["any", "some", "-", "many"], ans: 0, exp: "Signal: Negative sentence ('haven't') with uncountable noun -> 'any'." },
    { q: "11. We are late. The teacher will get angry with _______.", opts: ["we", "they", "us", "I"], ans: 2, exp: "Signal: 'We' + Preposition 'with' requires object pronoun -> 'us'." },
    { q: "12. My father is _______ engineer.", opts: ["a", "the", "-", "an"], ans: 3, exp: "Signal: Profession + Starts with vowel sound ('engineer') -> 'an'." },
    { q: "13. This is not my bicycle. It is my _______ bicycle.", opts: ["_", "father", "father'", "father's"], ans: 3, exp: "Signal: Indicates possession of a singular noun -> 'father's'." },
    { q: "14. Cats can wash _______ paws and fur.", opts: ["they", "his", "its", "their"], ans: 3, exp: "Signal: 'Cats' (plural) + Possessive adjective -> 'their'." },
    { q: "15. There is some milk. I'd like to drink _______.", opts: ["they", "it", "them", "its"], ans: 1, exp: "Signal: 'milk' (uncountable, singular) + Object position -> 'it'." },
    { q: "16. Terry is talking to two _______.", opts: ["women", "woman", "woman's", "women's"], ans: 0, exp: "Signal: Number 'two' requires plural noun -> 'women'." },
    { q: "17. All the _______ are following the man.", opts: ["policeman", "woman", "dog", "children"], ans: 3, exp: "Signal: 'are' indicates a plural subject -> 'children'." },
    { q: "18. There are many _______ on the shelf.", opts: ["paper", "magazines", "book", "dust"], ans: 1, exp: "Signal: 'many' requires a plural countable noun -> 'magazines'." },
    { q: "19. I can see a lot of _______ outside the building.", opts: ["person", "man", "people", "child"], ans: 2, exp: "Signal: Plural context without 's' -> Irregular plural 'people'." },
    { q: "20. There is a lot of ice in _______ refrigerator.", opts: ["a", "-", "an", "the"], ans: 3, exp: "Signal: Specific object in a typical room ('refrigerator') -> 'the'." },
    { q: "21. Give me two _______ cake, please.", opts: ["piece", "pieces", "slice", "pieces of"], ans: 3, exp: "Signal: 'two' + uncountable noun 'cake' -> 'pieces of'." },
    { q: "22. _______ students are looking for their ball.", opts: ["That", "Those", "This", "They"], ans: 1, exp: "Signal: Plural noun 'students' -> Demonstrative adjective 'Those'." },
    { q: "23. Please hand me _______ dictionary.", opts: ["that", "these", "it", "them"], ans: 0, exp: "Signal: Singular noun 'dictionary' -> Demonstrative adjective 'that'." },
    { q: "24. A: Is this your suitcase? B: No, _______ is my suitcase.", opts: ["that", "these", "it", "they"], ans: 0, exp: "Signal: Singular demonstrative pronoun replacing a farther object -> 'that'." },
    { q: "25. Bill and Jack are going to _______ house.", opts: ["they", "their", "them", "his"], ans: 1, exp: "Signal: 'Bill and Jack' (plural owners) -> Possessive 'their'." },
    { q: "26. My brother and I are hungry. _______ are thirsty too.", opts: ["They", "He", "We", "Us"], ans: 2, exp: "Signal: 'My brother and I' = Subject pronoun 'We'." },
    { q: "27. Take Janet and Anna to _______ rooms.", opts: ["her", "them", "they", "their"], ans: 3, exp: "Signal: 'Janet and Anna' (plural) -> Possessive 'their'." },
    { q: "28. Father is calling Ali and me. He wants _______.", opts: ["we", "us", "them", "him"], ans: 1, exp: "Signal: 'Ali and me' = Object pronoun 'us'." },
    { q: "29. Serpil dropped some books, so I picked _______ up for her.", opts: ["them", "it", "its", "they"], ans: 0, exp: "Signal: 'books' (plural) + Object position -> 'them'." },
    { q: "30. The boys are holding up _______ hands.", opts: ["their", "there", "they", "them"], ans: 0, exp: "Signal: 'boys' -> Possessive adjective 'their'." },
    { q: "31. Seda and I washed _______ hands.", opts: ["us", "our", "ours", "we"], ans: 1, exp: "Signal: 'Seda and I' = 'we' -> Possessive adjective 'our'." },
    { q: "32. Look at that house. All _______ windows are broken.", opts: ["their", "his", "it", "its"], ans: 3, exp: "Signal: 'house' (singular object) -> Possessive adjective 'its'." },
    { q: "33. The sea is dirty. There is oil on _______.", opts: ["them", "they", "it", "her"], ans: 2, exp: "Signal: 'The sea' (singular object) -> Object pronoun 'it'." },
    { q: "34. The girls can go home. They have finished _______ work.", opts: ["its", "ours", "hers", "their"], ans: 3, exp: "Signal: 'The girls' / 'They' -> Possessive adjective 'their'." },
    { q: "35. Do you want those shoes? I don't want _______.", opts: ["them", "they", "him", "its"], ans: 0, exp: "Signal: 'shoes' (plural) -> Object pronoun 'them'." },
    { q: "36. We called Allan. He came to _______.", opts: ["our", "us", "we", "ours"], ans: 1, exp: "Signal: 'We' + Preposition 'to' -> Object pronoun 'us'." },
    { q: "37. Look at these books. Are _______ yours?", opts: ["they", "them", "this", "that"], ans: 0, exp: "Signal: 'books' (plural) + Subject position in question -> 'they'." },
    { q: "38. We went to _______ seaside and played on the beach.", opts: ["a", "the", "an", "_"], ans: 1, exp: "Signal: Common place phrase -> 'the seaside'." },
    { q: "39. Many tourists visit _______ Turkey.", opts: ["a", "the", "an", "_"], ans: 3, exp: "Signal: Country names generally do not take articles -> No article (-)." },
    { q: "40. There is only _______ water in the glass. Please give me some more.", opts: ["many", "much", "a few", "a little"], ans: 3, exp: "Signal: 'water' (uncountable) + small amount needed ('some more') -> 'a little'." },
    { q: "41. There were not _______ people at the market yesterday.", opts: ["many", "much", "a few", "a little"], ans: 0, exp: "Signal: 'not' + plural countable noun ('people') -> 'many'." },
    { q: "42. I put _______ sugar on the fruit. I do not like sugar very much.", opts: ["many", "much", "a few", "a little"], ans: 3, exp: "Signal: 'sugar' (uncountable) + 'do not like... very much' -> 'a little'." },
    { q: "43. We can all get on the bus. There are only _______ passengers on it now.", opts: ["many", "much", "a few", "a little"], ans: 2, exp: "Signal: 'passengers' (plural countable) + small amount -> 'a few'." },
    { q: "44. The policeman is holding the _______ right arm.", opts: ["robber", "robber's", "robbers", "robbers'"], ans: 1, exp: "Signal: Singular possession ('arm of the robber') -> 'robber's'." },
    { q: "45. It was my _______ watch.", opts: ["grandfathers", "of grandfather", "grandfather's", "grandfather"], ans: 2, exp: "Signal: Singular possession -> 'grandfather's'." },
    { q: "46. I can see the _______ bicycles.", opts: ["boys'", "boys", "boy", "of the boys"], ans: 0, exp: "Signal: Plural possession ('bicycles of the boys') -> 'boys''." },
    { q: "47. I checked the answers. Two of _______ were wrong.", opts: ["it", "its", "them", "they"], ans: 2, exp: "Signal: 'answers' (plural) + After preposition 'of' -> 'them'." },
    { q: "48. The postman gave me two letters, so I gave _______ to my mother.", opts: ["them", "its", "they", "it"], ans: 0, exp: "Signal: 'two letters' (plural) + Object position -> 'them'." },
    { q: "49. The army lost the battle because _______ was not strong.", opts: ["they", "them", "it", "its"], ans: 2, exp: "Signal: 'The army' (singular collective noun) -> Subject 'it'." },
    { q: "50. My parents are coming. I'll open the door for _______.", opts: ["they", "them", "him", "her"], ans: 1, exp: "Signal: 'parents' (plural) + Object of preposition 'for' -> 'them'." },
    { q: "51. Is this radio _______?", opts: ["to you", "of you", "you", "yours"], ans: 3, exp: "Signal: Possessive pronoun without a following noun -> 'yours'." },
    { q: "52. Give that ball to Tom and me. It _______.", opts: ["is mine", "is ours", "is theirs", "is our"], ans: 1, exp: "Signal: 'Tom and me' = 'us'. Possessive pronoun -> 'ours'." },
    { q: "53. We washed _______ and then had our dinner.", opts: ["myself", "himself", "herself", "ourselves"], ans: 3, exp: "Signal: Subject 'We' -> Reflexive pronoun 'ourselves'." },
    { q: "54. You must learn to defend _______, Tom.", opts: ["yourself", "yourselves", "himself", "ourselves"], ans: 0, exp: "Signal: Singular 'You' (Tom) -> Reflexive pronoun 'yourself'." },
    { q: "55. I cut _______ on that piece of wire.", opts: ["himself", "myself", "oneself", "herself"], ans: 1, exp: "Signal: Subject 'I' -> Reflexive pronoun 'myself'." },
    { q: "56. I saw the girls, so I spoke to _______.", opts: ["she", "her", "they", "them"], ans: 3, exp: "Signal: 'the girls' (plural) + Object of preposition 'to' -> 'them'." },
    { q: "57. You can have these books. _______ are too hard for me.", opts: ["It", "They", "Its", "There"], ans: 1, exp: "Signal: 'books' (plural) + Subject position -> 'They'." },
    { q: "58. The rope was not very strong, so we did not use _______.", opts: ["them", "its", "they", "it"], ans: 3, exp: "Signal: 'The rope' (singular) + Object position -> 'it'." },
    { q: "59. The policeman spoke to my sister and me. He told _______ about the bridge.", opts: ["us", "he", "I", "we"], ans: 0, exp: "Signal: 'my sister and me' = Object pronoun 'us'." },
    { q: "60. The bananas were not ripe, so we did not buy _______.", opts: ["it", "its", "them", "they"], ans: 2, exp: "Signal: 'bananas' (plural) + Object position -> 'them'." },
    { q: "61. Please open the window. I can't reach _______.", opts: ["him", "her", "them", "it"], ans: 3, exp: "Signal: 'window' (singular object) -> 'it'." },
    { q: "62. My father listened to the news. He was very pleased with _______.", opts: ["them", "it", "they", "its"], ans: 1, exp: "Signal: 'news' (uncountable, singular) -> 'it'." },
    { q: "63. Can you tell me _______ best way to the station?", opts: ["a", "an", "the", "-"], ans: 2, exp: "Signal: Superlative adjective ('best') -> Article 'the'." },
    { q: "64. She works as _______ clerk in a very large bank.", opts: ["a", "an", "the", "-"], ans: 0, exp: "Signal: Profession + Starts with consonant ('clerk') -> 'a'." },
    { q: "65. Cyprus is _______ island in the Mediterranean.", opts: ["a", "an", "the", "-"], ans: 1, exp: "Signal: Singular countable noun starting with a vowel ('island') -> 'an'." },
    { q: "66. There is _______ excellent film on television this evening.", opts: ["a", "an", "the", "-"], ans: 1, exp: "Signal: Adjective starting with a vowel sound ('excellent') -> 'an'." },
    { q: "67. In England there is a saying: \"_______ apple a day keeps the doctor away\".", opts: ["a", "an", "the", "-"], ans: 1, exp: "Signal: Starts with a vowel ('apple') -> 'an'." },
    { q: "68. It is going to rain. I must buy _______ umbrella quickly.", opts: ["a", "an", "the", "-"], ans: 1, exp: "Signal: Starts with a vowel ('umbrella') -> 'an'." },
    { q: "69. _______ other day I had a letter from my friend.", opts: ["a", "an", "the", "-"], ans: 2, exp: "Signal: Fixed phrase indicating recent past -> 'The other day'." },
    { q: "70. They enjoyed _______ at the party.", opts: ["himself", "themselves", "them", "The"], ans: 1, exp: "Signal: Subject 'They' + verb 'enjoy' takes reflexive -> 'themselves'." },
    { q: "71. My friend cut _______ when she was cooking.", opts: ["myself", "himself", "herself", "her"], ans: 2, exp: "Signal: 'she' -> Reflexive pronoun 'herself'." },
    { q: "72. Help _______ to some more coffee.", opts: ["yourself", "myself", "you", "yours"], ans: 0, exp: "Signal: Imperative sentence implies 'You' -> Reflexive 'yourself'." },
    { q: "73. I taught _______ to play the guitar. I've never had lessons.", opts: ["me", "myself", "himself", "herself"], ans: 1, exp: "Signal: Subject 'I' -> Reflexive pronoun 'myself'." },
    { q: "74. The cow hurt _______ when it tried to get through the fence.", opts: ["himself", "herself", "itself", "themselves"], ans: 2, exp: "Signal: Animal ('cow' / 'it') -> Reflexive pronoun 'itself'." },
    { q: "75. That machine is automatic. It runs by _______.", opts: ["itself", "it", "themselves", "herself"], ans: 0, exp: "Signal: 'by' + reflexive means 'automatically/alone' -> 'by itself'." },
    { q: "76. She is wearing _______ unusual dress.", opts: ["a", "an", "the", "-"], ans: 1, exp: "Signal: Starts with a vowel sound ('unusual') -> 'an'." },
    { q: "77. The car was traveling at more than 90 miles _______ hour.", opts: ["a", "an", "the", "-"], ans: 1, exp: "Signal: Silent 'h' ('hour') -> 'an'." },
    { q: "78. It's _______ time for us to go home.", opts: ["a", "an", "the", "-"], ans: 3, exp: "Signal: Fixed phrase 'It's time' -> No article (-)." },
    { q: "79. This cake was made with _______ butter so it should be good.", opts: ["a", "an", "the", "-"], ans: 3, exp: "Signal: Uncountable noun ('butter') -> No article (-)." },
    { q: "80. His parents and _______ went to a concert last weekend.", opts: ["me", "our", "mine", "us"], ans: 0, exp: "Signal: Colloquial subject pronoun replacement -> 'me' (instead of standard 'I')." }
  ]
});
