window.TESTS=window.TESTS||[];
window.TESTS.push({
  name:"Intermediate Test 1",
  badge:"📘 Auxiliary verbs (do, be, have) · Prepositions",
  questions:[
    {q:"_____ you ever stayed at the Ritz?", opts:["Did","Have","Was","Were"], ans:1, exp:"Have + ever + V3 → Present Perfect for experience"},
    {q:"We _____ breakfast in bed.", opts:["were have","has","was having","had"], ans:3, exp:"had = Past Simple of 'have' (eat). We had breakfast."},
    {q:"_____ John give you those flowers?", opts:["Did","Have","Was","Is"], ans:0, exp:"Did + S + bare V → Past Simple question"},
    {q:"I _____ my homework very quickly last night.", opts:["do","have","did","am"], ans:2, exp:"did → Past Simple (last night = past time marker)"},
    {q:"She _____ a shower every morning before school.", opts:["does","has","did","is"], ans:1, exp:"has a shower = habit, Present Simple, 3rd person → has"},
    {q:"We _____ talking to James about his exam.", opts:["don't","haven't","wasn't","aren't"], ans:3, exp:"aren't + V-ing → Present Continuous negative"},
    {q:"Lots of trees _____ blown down by the wind.", opts:["were","has","did","is"], ans:0, exp:"were + V3 (blown) → Past Simple passive, plural subject"},
    {q:"Where _____ you yesterday?", opts:["was","have","did","were"], ans:3, exp:"you + were → Past Simple of 'be' (you always takes were)"},
    {q:"Mary never _____ the washing up.", opts:["does","has","did","is"], ans:0, exp:"does the washing up = Present Simple habit, 3rd person → does"},
    {q:"Thank goodness we _____ a dishwasher!", opts:["was","have","did","were"], ans:1, exp:"have a dishwasher = possession, Present Simple, we → have"},
    {q:"How many people _____ you invited to the party?", opts:["was","have","did","were"], ans:1, exp:"Have + you + V3 (invited) → Present Perfect question"},
    {q:"Why _____ you leaving so early?", opts:["was","have","is","are"], ans:3, exp:"are + you + V-ing (leaving) → Present Continuous question"},
    {q:"We _____ got a beautiful puppy called Molly.", opts:["was","have","did","were"], ans:1, exp:"have got = possession (British English). We have got = we own"},
    {q:"We _____ a beautiful puppy called Molly.", opts:["was","having","did","had"], ans:3, exp:"had = Past Simple (narrating). We had a puppy."},
    {q:"I have been to Australia but Anna _____.", opts:["haven't","hasn't","isn't","doesn't"], ans:1, exp:"hasn't → 3rd person singular negative of Present Perfect"},
    {q:"Anna likes ice-cream but John _____.", opts:["haven't","hasn't","isn't","doesn't"], ans:3, exp:"doesn't → 'likes' is Present Simple, negative needs doesn't"},
    {q:"I don't like ice-cream but Jill _____.", opts:["have","has","is","does"], ans:3, exp:"does → 'don't like' is Present Simple negative, affirmative echo = does"},
    {q:"Maria isn't studying hard but I _____.", opts:["have","has","am","are"], ans:2, exp:"am → 'isn't studying' is Continuous, echo for I = am"},
    {q:"John loves flying but we _____.", opts:["haven't","don't","isn't","doesn't"], ans:1, exp:"don't → 'loves' is Present Simple, we + negative = don't"},
    {q:"I watched TV last night but my sister _____.", opts:["hasn't","didn't","isn't","doesn't"], ans:1, exp:"didn't → 'watched' is Past Simple, negative echo = didn't"},
    {q:"Bill hasn't finished his work but we _____.", opts:["have","do","don't","doesn't"], ans:0, exp:"have → 'hasn't finished' is Present Perfect, affirmative echo = have"},
    {q:"We don't want to leave early but they _____.", opts:["have","do","is","does"], ans:1, exp:"do → 'don't want' is Present Simple negative, affirmative echo = do"},
    {q:"They didn't remember my birthday but you _____.", opts:["have","don't","did","does"], ans:2, exp:"did → 'didn't remember' is Past Simple, affirmative echo = did"},
    {q:"Your English is really improving but mine _____.", opts:["haven't","don't","isn't","doesn't"], ans:2, exp:"isn't → 'is improving' is Present Continuous, negative echo = isn't"},
    {q:"_____ you speak three languages?", opts:["Do","Does","Did","Are"], ans:0, exp:"Do + you + bare V → Present Simple question"},
    {q:"_____ you having a holiday soon?", opts:["Do","Does","Did","Are"], ans:3, exp:"Are + you + V-ing → Present Continuous question"},
    {q:"_____ you have a good holiday last year?", opts:["Do","Does","Did","Are"], ans:2, exp:"Did + you + bare V → Past Simple question (last year)"},
    {q:"_____ you ever been to Amsterdam?", opts:["Do","Does","Have","Did"], ans:2, exp:"Have + you + ever + V3 → Present Perfect for experience"},
    {q:"_____ you often travel abroad?", opts:["Do","Does","Have","Did"], ans:0, exp:"Do + you + bare V → Present Simple (habit: often)"},
    {q:"_____ your best friend sometimes go on holiday with you?", opts:["Do","Does","Have","Did"], ans:1, exp:"Does + 3rd person singular subject + bare V → Present Simple"},
    {q:"I think you're wrong. I don't agree _____ you at all.", opts:["to","on","with","about"], ans:2, exp:"agree WITH someone"},
    {q:"I'm not interested _____ what you think or what you want.", opts:["to","on","with","in"], ans:3, exp:"interested IN something"},
    {q:"We might have a picnic. It depends _____ the weather.", opts:["to","on","with","about"], ans:1, exp:"depend ON something"},
    {q:"What are you listening _____ ?", opts:["to","on","with","about"], ans:0, exp:"listen TO something"},
    {q:"If you have a problem, talk _____ the teacher.", opts:["to","on","at","in"], ans:0, exp:"talk TO someone (a person)"},
    {q:"\"What did you talk _____ ?\" \"Oh, this and that.\"", opts:["to","on","with","about"], ans:3, exp:"talk ABOUT something (a topic)"},
    {q:"You aren't concentrating on your work. What are you thinking _____?", opts:["to","on","with","about"], ans:3, exp:"think ABOUT something (what's on your mind)"},
    {q:"\"What do you think _____ Pete?\" \"I really like him.\"", opts:["to","at","with","of"], ans:3, exp:"think OF someone (opinion/impression)"},
    {q:"Where's the cash desk? I'd like to pay _____ this book.", opts:["to","for","with","about"], ans:1, exp:"pay FOR something"},
    {q:"\"I've lost your pen. Sorry...\" \"It's all right. Don't worry _____ it.\"", opts:["to","on","with","about"], ans:3, exp:"worry ABOUT something"}
  ]
});
