window.TESTS=window.TESTS||[];
window.TESTS.push({
  name:"Intermediate Test 2",
  badge:"\u{1F4D8} Present Simple/Continuous · Present Passive · Prepositions",
  questions:[
    {q:"Sue and Geoff _____ a shop.",opts:["work","study","run","runs"],ans:2,exp:"'run a shop' = manage/operate a shop. Present Simple for regular facts; plural subject → base form."},
    {q:"This kind of shop _____ a milk bar.",opts:["is called","called","is calling","is being called"],ans:0,exp:"Present Passive: S + is/are + past participle. 'is called' = named."},
    {q:"Most days the shop _____ at 10.00 p.m.",opts:["sells","opened","closes","run"],ans:2,exp:"Present Simple for daily routine. 'The shop' = 3rd person singular → closes (adds -s)."},
    {q:"They _____ camping any more.",opts:["go","doesn't go","don't go","have gone"],ans:2,exp:"Present Simple negative with plural subject: They + don't + base verb."},
    {q:"Ursula _____ four brothers and sisters.",opts:["have","has","haven't","having"],ans:1,exp:"Present Simple, 3rd person singular → 'has' (irregular form of 'have')."},
    {q:"It _____ her fifteen minutes _____ to school.",opts:["took / go","has taken / walk","takes / walk","takes / to walk"],ans:3,exp:"Fixed structure: It takes + someone + time + to + infinitive."},
    {q:"She _____ school at 7:45 a.m.",opts:["go","begin","starts","goes"],ans:2,exp:"Present Simple, 3rd person singular (she) → verb + s. 'Start school' = begin the school day."},
    {q:"I _____ lunch in the university canteen.",opts:["eats","have","drink","has"],ans:1,exp:"Present Simple, 1st person (I) → base form 'have'. 'Have lunch' = eat lunch."},
    {q:"I _____ extra money teaching computer studies.",opts:["earn","earns","win","buy"],ans:0,exp:"Present Simple, 1st person → base form. 'Earn' = receive money for work (not 'win')."},
    {q:"I _____ the traffic in Bangkok.",opts:["play","have","hate","has"],ans:2,exp:"Present Simple for feelings/states. 'Hate' = strongly dislike. 1st person → base form."},
    {q:"English is _____ here.",opts:["speak","spoke","is speaking","spoken"],ans:3,exp:"Passive: is + past participle. 'is spoken' (speak-spoke-spoken)."},
    {q:"Volvos are _____ in Sweden.",opts:["produced","produce","produces","producing"],ans:0,exp:"Passive: are + past participle. 'are produced' = manufactured."},
    {q:"Is service _____ in the bill?",opts:["including","include","to include","included"],ans:3,exp:"Passive question: Is + subject + past participle? 'Is service included?'"},
    {q:"Our kitchen _____ decorated at the moment.",opts:["is","is being","being","was being"],ans:1,exp:"Present Continuous Passive: is being + V3. 'At the moment' signals an action in progress now."},
    {q:"Our factory is being _____ over by an American company.",opts:["taken","bought","sold","run"],ans:0,exp:"Phrasal verb 'take over' = acquire control. Present Continuous Passive: is being taken over."},
    {q:"About one thousand people are _____ in the factory.",opts:["taken","cleaned","employed","worked"],ans:2,exp:"Passive: are + employed (= hired/given jobs). Note: 'worked' is not used in passive this way."},
    {q:"Lots of tulips are _____ in Holland.",opts:["grown","growing","grow","grew"],ans:0,exp:"Passive: are + grown (grow-grew-grown). Tulips are grown = cultivated."},
    {q:"That block of flats is being _____ because it is unsafe.",opts:["pulled down","pulled","pulled up","pulling down"],ans:0,exp:"Phrasal verb 'pull down' = demolish. Present Continuous Passive: is being pulled down."},
    {q:"In Britain milk is _____ to your doorstep.",opts:["shown","sold","bought","delivered"],ans:3,exp:"Passive: is + delivered (= brought to your door). Collocates with 'to your doorstep'."},
    {q:"When you _(20)_ at an airport ...",opts:["start","started","arrive","are arrived"],ans:2,exp:"Active Present Simple: 'you arrive'. 'Arrive' is intransitive — no passive form.",passage:"When you _(20)_ at an airport, you should go straight to the check-in desk where your ticket and luggage _(21)_. You _(22)_ your hand luggage with you but your suitcases _(23)_ to the plane on a conveyor belt. You can now go to the departure lounge. If you are on an international flight, your passport _(24)_, and then you and your bags _(25)_ by security cameras; sometimes you _(26)_ a body search and your luggage _(27)_ by a security officer. You _(28)_ in the departure lounge until your flight _(29)_ and you _(30)_ which gate number to go. Finally you _(31)_ your plane and you _(32)_ your seat by a flight attendant."},
    {q:"... your ticket and luggage _(21)_.",opts:["are checked","control","check","is changed"],ans:0,exp:"Passive: plural subject (ticket and luggage) → are + past participle. 'Are checked' = inspected."},
    {q:"You _(22)_ your hand luggage with you ...",opts:["kept","keeping","wait","keep"],ans:3,exp:"Active Present Simple: You + base verb. 'Keep' = retain/hold with you."},
    {q:"... your suitcases _(23)_ to the plane on a conveyor belt.",opts:["take","took","are taken","taking"],ans:2,exp:"Passive: plural subject → are + past participle. Suitcases are taken (not by you — by staff)."},
    {q:"... your passport _(24)_ ...",opts:["check","checked","is checking","is checked"],ans:3,exp:"Passive: singular subject → is + past participle. Your passport is checked (by officials)."},
    {q:"... you and your bags _(25)_ by security cameras ...",opts:["are x-rayed","x-rayed","control","check"],ans:0,exp:"Passive with 'by' agent: subject + are + V3 + by. 'Are x-rayed by security cameras'."},
    {q:"... sometimes you _(26)_ a body search ...",opts:["give","are given","gave","giving"],ans:1,exp:"Passive: You are given (= someone gives you). Indirect object becomes passive subject."},
    {q:"... your luggage _(27)_ by a security officer.",opts:["is searched","searching","searched","search"],ans:0,exp:"Passive: singular subject + is + V3 + by agent. 'Your luggage is searched by a security officer'."},
    {q:"You _(28)_ in the departure lounge ...",opts:["waiting","waits","wait","waited"],ans:2,exp:"Active Present Simple: You + base verb. 'You wait' — the subject performs the action."},
    {q:"... until your flight _(29)_ ...",opts:["calling","call","is called","called"],ans:2,exp:"Passive: Your flight is called (= announced over speakers). Singular → is + V3."},
    {q:"... you _(30)_ which gate number to go.",opts:["are told","telling","told","tell"],ans:0,exp:"Passive: You are told (= someone tells you). 'By' agent omitted but implied."},
    {q:"Finally you _(31)_ your plane ...",opts:["boarded","boarding","sit","board"],ans:3,exp:"Active Present Simple: You + base verb. 'Board' = get on (a plane/ship)."},
    {q:"... you _(32)_ your seat by a flight attendant.",opts:["show","are shown","showing","come"],ans:1,exp:"Passive: You are shown your seat (= a flight attendant shows you). 'By' agent present."},
    {q:"\"Hello. Can I speak to Mr. James?\" \"I'm sorry. He isn't _____ at the moment.\"",opts:["in","on","at","off"],ans:0,exp:"'be in' = be present at home/office. 'He isn't in' = he's not here right now."},
    {q:"\"He is _____ on holiday at the moment.\"",opts:["in","on","away","off"],ans:2,exp:"'be away' = not here, gone somewhere else. Often paired with 'on holiday/business'."},
    {q:"\"What's _____ at the moment?\" (cinema)",opts:["in","on","at","off"],ans:1,exp:"'be on' = currently showing/playing (films, TV programmes, events)."},
    {q:"I think this milk's _____ . It smells horrid.",opts:["in","on","at","off"],ans:3,exp:"'be off' = gone bad/sour (food/drink). The milk is off = it has spoiled."},
    {q:"\"Where shall we go for a meal?\" \"It's _____ you.\"",opts:["in","on","at","up to"],ans:3,exp:"'be up to someone' = it's your decision/choice. Fixed expression."},
    {q:"Come on, kids! Aren't you _____ yet?",opts:["in","on","up","off"],ans:2,exp:"'be up' = be awake and out of bed. 'Aren't you up yet?' = haven't you woken up?"},
    {q:"There must be someone _____ .",opts:["in","on","at","off"],ans:0,exp:"'be in' = be at home/inside. 'Someone must be in' = someone is home."},
    {q:"All the lights are _____ . I can see nothing.",opts:["in","on","at","off"],ans:3,exp:"'be off' = switched off/not working. Lights are off → darkness."},
    {q:"I must be _____ soon. I want to get to the shops.",opts:["in","on","at","off"],ans:3,exp:"'be off' = leave/depart. 'I must be off' = I need to go soon."},
    {q:"\"The central heating is _____ . That's why.\" (no hot water)",opts:["in","on","at","off"],ans:3,exp:"'be off' = switched off/not running. Heating is off → no hot water."},
    {q:"\"You're crying. What's _____ ?\" \"I'm just sad.\"",opts:["in","on","up","off"],ans:2,exp:"'What's up?' = What's wrong? / What's happening? Fixed informal expression."}
  ]
});
