window.TESTS=window.TESTS||[];
window.TESTS.push({
  name:"Intermediate Test 3",
  badge:"📘 While/During/For · Past Tenses · Past Passive · Prepositions",
  questions:[
    {q:"My uncle died _____ the war.", opts:["via","during","for","in"], ans:1, exp:"DURING + noun (the war = a noun phrase)."},
    {q:"The phone rang _____ I was having supper.", opts:["while","during","for","in"], ans:0, exp:"WHILE + clause (subject + verb: I was having supper)."},
    {q:"I lived in Paris _____ several years.", opts:["while","during","for","in"], ans:2, exp:"FOR + duration (several years = measurable time)."},
    {q:"_____ I was in Paris, I made a lot of friends.", opts:["While","During","For","In"], ans:0, exp:"WHILE + clause (I was in Paris)."},
    {q:"I was in hospital _____ three weeks.", opts:["while","during","for","in"], ans:2, exp:"FOR + duration (three weeks = measurable time)."},
    {q:"_____ my stay in hospital, the nurses looked after me very well.", opts:["While","During","For","In"], ans:1, exp:"DURING + noun (my stay = a noun phrase)."},
    {q:"A football match lasts _____ ninety minutes.", opts:["while","during","for","in"], ans:2, exp:"FOR + duration (ninety minutes = measurable time)."},
    {q:"I hurt my leg _____ I was playing football yesterday.", opts:["while","during","for","in"], ans:0, exp:"WHILE + clause (I was playing football)."},
    {q:"I hurt my leg _____ the second half of the match.", opts:["while","during","for","in"], ans:1, exp:"DURING + noun (the second half)."},
    {q:"Traffic is always bad _____ the rush hour.", opts:["while","during","for","in"], ans:1, exp:"DURING + noun (the rush hour)."},
    {q:"Last week I was held up _____ three hours.", opts:["while","during","for","in"], ans:2, exp:"FOR + duration (three hours = measurable time)."},
    {q:"Peter came round _____ we were eating.", opts:["while","during","in","on"], ans:0, exp:"WHILE + clause (we were eating)."},
    {q:"Peter came round _____ the meal.", opts:["while","during","on","in"], ans:1, exp:"DURING + noun (the meal)."},
    {q:"It's my birthday _____ next week.", opts:["at","in","on","-"], ans:3, exp:"No preposition before next/last/this/every."},
    {q:"\"When?\" \"_____ Monday.\"", opts:["At","In","On","-"], ans:2, exp:"ON + day of the week. On Monday."},
    {q:"_____ when were you born?", opts:["at","in","on","-"], ans:3, exp:"No preposition before question word 'when'."},
    {q:"_____ 8.00 _____ the morning.", opts:["At / in","In / in","On / in","- / in"], ans:0, exp:"AT + time / IN + part of day. At 8:00 in the morning."},
    {q:"I'm meeting Alan _____ this evening.", opts:["at","in","on","-"], ans:3, exp:"No preposition before next/last/this/every."},
    {q:"\"What time?\" \"_____ six.\"", opts:["At","In","On","-"], ans:0, exp:"AT + specific time. At six."},
    {q:"What did you do _____ the weekend?", opts:["at","in","with","-"], ans:0, exp:"AT the weekend (British English)."},
    {q:"_____ Friday evening we went to a party.", opts:["at","in","on","-"], ans:2, exp:"ON + specific day. On Friday evening."},
    {q:"We slept late _____ Saturday morning.", opts:["at","in","on","-"], ans:2, exp:"ON + day + part of day. On Saturday morning."},
    {q:"_____ the afternoon we went shopping.", opts:["At","In","On","-"], ans:1, exp:"IN + part of day. In the afternoon."},
    {q:"_____ 7:00 some friends came round for a drink.", opts:["At","In","On","-"], ans:0, exp:"AT + specific time. At 7:00."},
    {q:"We didn't do anything _____ Sunday.", opts:["at","in","on","-"], ans:2, exp:"ON + day of the week. On Sunday."},
    {q:"The weather in England is unreliable. _____ summer it can be hot, but it often rains _____ April and June.", opts:["At / in","In / in","On / in","- / in"], ans:1, exp:"IN + season / IN + month. In summer, in April."},
    {q:"_____ last year the summer was awful.", opts:["At","In","On","-"], ans:3, exp:"No preposition before next/last/this/every."},
    {q:"The best English weather is _____ spring and autumn.", opts:["at","in","on","-"], ans:1, exp:"IN + season. In spring and autumn."},
    {q:"I learned to drive _____ 1980 _____ the age of 17.", opts:["at / at","in / at","on / at","- / at"], ans:1, exp:"IN + year / AT + age. In 1980, at the age of 17."},
    {q:"My brother learned _____ the same time as me.", opts:["at","in","on","-"], ans:0, exp:"AT the same time (fixed expression)."},
    {q:"I'll phone you _____ next week. _____ Thursday.", opts:["at / On","in / On","on / On","- / On"], ans:3, exp:"No preposition (next week) / ON + day of the week."},
    {q:"I'll phone you _____ about 3.00.", opts:["at","in","on","-"], ans:0, exp:"AT + specific time. At about 3:00."},
    {q:"33. Helen Keller's deafness and blindness _____ by a severe illness when she was a baby.", opts:["cause","caused","were caused","has caused"], ans:2, exp:"Past Passive: were caused (subject received the action).", passage:"Helen Keller's deafness and blindness _(33)_ by a severe illness when she was a baby. Her parents _(34)_ what to do, and they _(35)_ it difficult to control their growing daughter. One day they _(36)_ about a brilliant young teacher called Anne Sullivan. She _(37)_ to work with Helen. Very firmly and patiently, she _(38)_ her that every object _(39)_ a name. Eventually Helen _(40)_ a place at university. After this she _(41)_ the world helping people like herself. In 1962 the story of her life _(42)_ into a film, The Miracle Worker."},
    {q:"34. Her parents _____ what to do.", opts:["didn't know","doesn't know","knew","knows"], ans:0, exp:"Past Simple negative: didn't know (past narrative)."},
    {q:"35. They _____ it difficult to control their growing daughter.", opts:["find","finds","were found","found"], ans:3, exp:"Past Simple: found (past narrative, active voice)."},
    {q:"36. One day they _____ about a brilliant young teacher called Anne Sullivan.", opts:["tell","were told","telling","told"], ans:1, exp:"Past Passive: were told (they received the information)."},
    {q:"37. She _____ to work with Helen.", opts:["came","began","start","helping"], ans:0, exp:"Past Simple: came (she came to work with Helen)."},
    {q:"38. Very firmly and patiently, she _____ her that every object had a name.", opts:["studied","helped","thought","taught"], ans:3, exp:"Past Simple: taught (past of teach; she taught her)."},
    {q:"39. She taught her that every object _____ a name.", opts:["has","had","have","having"], ans:1, exp:"Past Simple: had (reported speech, backshift from has)."},
    {q:"40. Eventually Helen _____ a place at university.", opts:["offer","offered","was offered","offering"], ans:2, exp:"Past Passive: was offered (Helen received the offer)."},
    {q:"41. After this she _____ the world helping people like herself.", opts:["tour","toured","touring","tours"], ans:1, exp:"Past Simple: toured (she toured the world)."},
    {q:"42. In 1962 the story of her life _____ into a film, The Miracle Worker.", opts:["was made","make","is making","was making"], ans:0, exp:"Past Passive: was made (the story was made into a film)."},
  ]
});
