window.TESTS=window.TESTS||[];
window.TESTS.push({
  name:"Intermediate Test 5",
  badge:"\u{1F4D8} Make/Do · Prepositions · Indefinite Pronouns · Infinitive/Gerund",
  questions:[
    {q:"Is there a public call box near here? I have to _____ a phone call.", opts:["do","make","get","hear"], ans:1, exp:"MAKE a phone call (make + communication/creation)"},
    {q:"First she said 'Yes', then she said 'No', but in the end she _____ up her mind to marry him.", opts:["did","made","got","said"], ans:1, exp:"MAKE up one's mind = decide (fixed expression)"},
    {q:"When you're not sure what to do, the best thing is to _____ nothing.", opts:["do","make","get","hear"], ans:0, exp:"DO nothing (do + general actions)"},
    {q:"Ssh! You mustn't _____ a noise. The baby's asleep.", opts:["do","make","get","hear"], ans:1, exp:"MAKE a noise (make + sounds/disturbances)"},
    {q:"My teacher says I must work harder, but I can't work any harder. I'm _____ my best.", opts:["doing","trying","making","showing"], ans:0, exp:"DO one's best (do + effort/performance)"},
    {q:"We asked to see the manager and we _____ a complaint about the terrible service.", opts:["did","made","had","heard"], ans:1, exp:"MAKE a complaint (make + formal communication)"},
    {q:"At first I found learning English very easy, but now I don't think I'm _____ any progress at all.", opts:["doing","making","showing","getting"], ans:1, exp:"MAKE progress (make + achievement/change)"},
    {q:"Could you _____ me a favor please? Could you give me a lift to the airport?", opts:["make","do","give","want"], ans:1, exp:"DO someone a favor (do + helpful action)"},
    {q:"My uncle died without _____ a will.", opts:["doing","make","get","making"], ans:3, exp:"MAKE a will (make + creating a document)"},
    {q:"We have some lovely new neighbors; we've already _____ friends with them.", opts:["did","made","done","make"], ans:1, exp:"MAKE friends (make + relationships)"},
    {q:"I _____ to keep fit, so I _____ exercises every day.", opts:["do","make","get","hear"], ans:0, exp:"DO exercises (do + physical/routine activity)"},
    {q:"Before you go on holiday, you should _____ sure that the doors and windows are shut.", opts:["do","make","get","hear"], ans:1, exp:"MAKE sure (fixed expression: make sure/certain)"},
    {q:"_____ money, not war!", opts:["Do","Make","Study","Get"], ans:1, exp:"MAKE money (make + producing value/wealth)"},
    {q:"I was _____ a queue waiting to buy some bread.", opts:["in","on","at","by"], ans:0, exp:"IN a queue (in + lines/rows of people)"},
    {q:"I looked _____ the shelves and _____ all the cupboards.", opts:["in / on","on / in","at / in","at / on"], ans:1, exp:"ON the shelves (surface) / IN the cupboards (enclosed space)"},
    {q:"They certainly weren't _____ the table or _____ the floor.", opts:["in / on","on / in","at / on","on / on"], ans:3, exp:"ON the table / ON the floor (on + flat surfaces)"},
    {q:"Had I left them _____ work?", opts:["in","on","at","near"], ans:2, exp:"AT work (at + workplace/general location)"},
    {q:"Were they _____ the car?", opts:["in","on","at","of"], ans:0, exp:"IN the car (in + enclosed vehicles)"},
    {q:"Then I realized where they were. They were _____ my favorite armchair.", opts:["in","on","at","off"], ans:0, exp:"IN an armchair (in + seats you sink into)"},
    {q:"\"Where were you at 2.00?\" \"_____ the beach.\"", opts:["in","on","at","to"], ans:1, exp:"ON the beach (on + open flat areas/surfaces)"},
    {q:"\"Where were you at 2.00?\" \"_____ Sally's house doing my homework.\"", opts:["in","on","at","from"], ans:2, exp:"AT Sally's house (at + someone's home/address)"},
    {q:"\"Where were you at 2.00?\" \"_____ a cave.\"", opts:["in","on","at","by"], ans:0, exp:"IN a cave (in + enclosed/covered spaces)"},
    {q:"Would you like _____ to eat?", opts:["something","anything","nothing","everything"], ans:0, exp:"something — offers/requests use some- (Would you like...?)"},
    {q:"Can I have _____ to drink?", opts:["something","anything","nothing","everything"], ans:0, exp:"something — polite requests use some- (Can I have...?)"},
    {q:"Can we go _____ quiet?", opts:["somewhere","anywhere","nowhere","everywhere"], ans:0, exp:"somewhere — polite requests/suggestions use some-"},
    {q:"If you need _____ , just ask.", opts:["something","anything","nothing","everything"], ans:1, exp:"anything — conditionals (if-clauses) use any-"},
    {q:"Come and see me _____ you want. I don't mind.", opts:["some time","any time","no time","every time"], ans:1, exp:"any time — meaning 'whenever you like' (free choice)"},
    {q:"Help yourself to food. You can have _____ you want.", opts:["something","anything","nothing","everything"], ans:1, exp:"anything — free choice meaning 'whatever you like'"},
    {q:"_____ will tell you that two and two is four.", opts:["Someone","Anyone","No one","Nothing"], ans:1, exp:"Anyone — free choice meaning 'any person at all' (obvious fact)"},
    {q:"\"Does _____ want a game of tennis?\" \"Yes.\"", opts:["someone","anyone","no one","everyone"], ans:1, exp:"anyone — questions use any-"},
    {q:"Did _____ phone me while I was out?", opts:["someone","anyone","no one","everyone"], ans:1, exp:"anyone — questions use any-"},
    {q:"What's that smell? Can you smell _____ burning?", opts:["something","anything","nothing","everything"], ans:0, exp:"something — the speaker believes/expects it exists"},
    {q:"I asked if _____ wanted an ice-cream, but _____ did, so I just bought one for myself.", opts:["anyone / no one","no one / somebody","anybody / somebody","no body / no one"], ans:0, exp:"anyone (in the question) + no one (negative answer)"},
    {q:"Your face looks terribly familiar. Haven't I seen you _____ before?", opts:["somewhere","anywhere","nowhere","everywhere"], ans:0, exp:"somewhere — the speaker expects/believes it (positive meaning)"},
    {q:"She left the room without saying _____ .", opts:["something","anything","nothing","everything"], ans:1, exp:"anything — after 'without' (implicit negative) use any-"},
    {q:"This doesn't look a very nice restaurant. Can we go _____ else?", opts:["somewhere","anywhere","nowhere","everywhere"], ans:0, exp:"somewhere else — suggestions/requests use some-"},
    {q:"I have _____ more to say to you. Goodbye!", opts:["something","anything","nothing","everything"], ans:2, exp:"nothing = not anything (negative meaning without 'not')"},
    {q:"I have never been _____ more beautiful than Scotland.", opts:["somewhere","anywhere","nowhere","everywhere"], ans:1, exp:"anywhere — after 'never' (negative context) use any-"},
    {q:"I felt so embarrassed. _____ was laughing at me.", opts:["Everyone","Anyone","No one","Something"], ans:0, exp:"Everyone = all people (the whole group was laughing)"},
    {q:"\"What do you want for supper?\" \"_____ . I don't mind.\"", opts:["Something","Anything","Nothing","Everything"], ans:1, exp:"Anything — free choice meaning 'I don't care which'"},
    {q:"It was Sunday, and the town was deserted. _____ was in the streets, and _____ was open.", opts:["Somebody / somewhere","Anybody / anywhere","Nobody / nowhere","Everybody / everywhere"], ans:2, exp:"Nobody/nowhere — deserted means empty (negative meaning)"},
    {q:"\"Who was at the party?\" \"_____ , Pete, Ann, James...\"", opts:["Someone","Anyone","No one","Everyone"], ans:3, exp:"Everyone — listing all people = everyone was there"},
    {q:"\"Where do you want to go on holiday?\" \"_____ hot.\"", opts:["Somebody","Anywhere","Nowhere","Everywhere"], ans:1, exp:"Anywhere — free choice meaning 'any place, as long as it's hot'"},
    {q:"I want _____ more careful with your homework in future.", opts:["you be","you to be","that you are","you being"], ans:1, exp:"want + object + to V (infinitive pattern)"},
    {q:"I stopped _____ when I was thirty.", opts:["to smoke","smoke","smoking","too smoke"], ans:2, exp:"stop + V-ing = stop doing the activity (quit the habit)"},
    {q:"Why did I agree _____ with you? I can't stand it.", opts:["to work","work","working","to working"], ans:0, exp:"agree + to V (infinitive — agree is followed by to-infinitive)"},
    {q:"I'm really looking forward to _____ my new course.", opts:["start","starting","started","to start"], ans:1, exp:"look forward to + V-ing ('to' here is a preposition, not infinitive)"},
    {q:"They can't help us _____ the house.", opts:["move","moving","moved","move to"], ans:0, exp:"help + object + bare infinitive (V without 'to')"},
    {q:"She refused _____ the phone.", opts:["answer","to answer","answered","answering"], ans:1, exp:"refuse + to V (infinitive — refuse always takes to-infinitive)"},
    {q:"I don't mind _____ to the restaurant.", opts:["driving","drive","drove","to drive"], ans:0, exp:"mind + V-ing (gerund — mind is followed by -ing form)"},
    {q:"We encouraged them _____ a new business.", opts:["setting up","to set up","set up","'d set up"], ans:1, exp:"encourage + object + to V (infinitive pattern)"},
    {q:"His parents don't allow him _____ after ten o'clock.", opts:["stay up","to stay up","stay up","stayed up"], ans:1, exp:"allow + object + to V (infinitive pattern)"}
  ]
});
